// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACCb2djGW0OhLGRTSZNa4qe6JuCNP2BIk',
    appId: '1:1057646222111:web:e1c38db43f60181468ee2a',
    messagingSenderId: '1057646222111',
    projectId: 'mobileappcalc',
    authDomain: 'mobileappcalc.firebaseapp.com',
    storageBucket: 'mobileappcalc.firebasestorage.app',
    measurementId: 'G-ZW842KHM0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFMLRQ34tAv7BqcmUJtEPm4i8AkRIKtgE',
    appId: '1:1057646222111:android:9692d12b8a187ebb68ee2a',
    messagingSenderId: '1057646222111',
    projectId: 'mobileappcalc',
    storageBucket: 'mobileappcalc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7Hqi6bHwBzX-NeiOlYfuQ4ZHwnKKDmo8',
    appId: '1:1057646222111:ios:8e9d1ab25759701068ee2a',
    messagingSenderId: '1057646222111',
    projectId: 'mobileappcalc',
    storageBucket: 'mobileappcalc.firebasestorage.app',
    iosBundleId: 'com.example.calculatorMobApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7Hqi6bHwBzX-NeiOlYfuQ4ZHwnKKDmo8',
    appId: '1:1057646222111:ios:8e9d1ab25759701068ee2a',
    messagingSenderId: '1057646222111',
    projectId: 'mobileappcalc',
    storageBucket: 'mobileappcalc.firebasestorage.app',
    iosBundleId: 'com.example.calculatorMobApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACCb2djGW0OhLGRTSZNa4qe6JuCNP2BIk',
    appId: '1:1057646222111:web:5cdbef033437a9cf68ee2a',
    messagingSenderId: '1057646222111',
    projectId: 'mobileappcalc',
    authDomain: 'mobileappcalc.firebaseapp.com',
    storageBucket: 'mobileappcalc.firebasestorage.app',
    measurementId: 'G-V5QZM7D86Q',
  );
}
